import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :council_hub_ui, CouncilHubUiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# The https redirect is opt-in at runtime (COUNCIL_FORCE_SSL=true, read in
# config/runtime.exs and enforced by CouncilHubUiWeb.Plugs.MaybeForceSsl — the
# endpoint's :force_ssl option is compile-time, so it can't be toggled by env).
# This server does not terminate TLS itself — the documented deployment is direct
# http access over a LAN/tailnet IP (e.g. http://100.x.x.x:4000) — so forcing it
# unconditionally here would redirect any non-localhost host to an https:// this
# process never serves. Enable it only when a reverse proxy sets X-Forwarded-Proto.

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
